opengl: false
theme: dark
use_exec: false
checkpoints: models/checkpoints
controlnet: models/controlnet
embeddings: models/embeddings
hypernetworks: models/hypernetworks
loras: models/loras
output: output
t2i_adapter: models/t2i_adapter
upscalers: models/upscalers
vae: models/vae